general:
  kafka-topic: test-topic

spring:
  datasource:
    url: jdbc:h2:mem:midasdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
